# Generated by Django 4.2.2 on 2023-06-19 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currencies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto_currency',
            old_name='preivous_day_price',
            new_name='previous_day_price',
        ),
    ]
