# Generated by Django 4.2.2 on 2023-06-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_currencies', '0002_rename_preivous_day_price_crypto_currency_previous_day_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_currency',
            name='abbreviation',
            field=models.CharField(max_length=15),
        ),
    ]
